// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjbPQIk87ZjSQSCtPciir6qdu2PM4Dgb8',
    appId: '1:579126736241:web:16ddf30fa08e83037b32d0',
    messagingSenderId: '579126736241',
    projectId: 'arinterior-ea12f',
    authDomain: 'arinterior-ea12f.firebaseapp.com',
    storageBucket: 'arinterior-ea12f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUDEDae9DqKzhRduGpEngFzTxUncnBBYU',
    appId: '1:579126736241:android:76b35382b752ebf97b32d0',
    messagingSenderId: '579126736241',
    projectId: 'arinterior-ea12f',
    storageBucket: 'arinterior-ea12f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA48uvAYmrT1Rc6y89EmCiiIYvdveGqMP4',
    appId: '1:579126736241:ios:e2b88ea8e5c956237b32d0',
    messagingSenderId: '579126736241',
    projectId: 'arinterior-ea12f',
    storageBucket: 'arinterior-ea12f.firebasestorage.app',
    iosBundleId: 'com.example.arHomeDecoration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjbPQIk87ZjSQSCtPciir6qdu2PM4Dgb8',
    appId: '1:579126736241:web:3bdeebbd34fd558c7b32d0',
    messagingSenderId: '579126736241',
    projectId: 'arinterior-ea12f',
    authDomain: 'arinterior-ea12f.firebaseapp.com',
    storageBucket: 'arinterior-ea12f.firebasestorage.app',
  );
}
